name: submission-ui
namespace: development

image:
  tag: 0.1

labels:
  subsystem: submission
  service_group: frontend

replicas: 1

authenticator:
  service: authenticator

ingress:
  name: submission-ui
  host: changeme
  path: /
