version: '3.4'
x-base-service:
  &base-service
  stdin_open: true
  tty: true
  environment:
    SECRET_KEY: "not secure only use for development"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    REDIS_ENDPOINT: "submission-ui-redis"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    COMPILER_DOCKER_IMAGE: "${COMPILER_DOCKER_IMAGE}"
    HOST_SOURCE_ROOT: "${HOST_SOURCE_ROOT}"
    AWS_S3_REGION_NAME: "us-east-1"
    S3_ENDPOINT: "https://compiler-localstack:4572"
    S3_VERIFY: 0
    FILE_MANAGER_ENDPOINT: "http://arxiv-filemanager:8000/filemanager/api"
    FILE_MANAGER_CONTENT_PATH: "/{source_id}"
    LOGLEVEL: 10
    FLASK_APP: /opt/arxiv/app.py
    FLASK_DEBUG: 1
    VERBOSE_COMPILE: 1
    JWT_SECRET: "foosecret"
    # CLASSIC_DATABASE_URI: "mysql+mysqldb://foouser:foopass@submission-ui-maria:3306/submission?charset=utf8"
    CLASSIC_DATABASE_URI: "sqlite:///db.sqlite"
    FLASK_SECRET: 'what'
    SESSION_COOKIE_SECURE: 0
    COMPILER_ENDPOINT: "http://compiler-api:8100/"

services:
  submission-ui-redis:
    image: redis
    container_name: submission-ui-redis
    networks:
      - arxiv-submission-ui

  submission-ui-maria:
    image: mariadb:10.3
    container_name: submission-ui-maria
    networks:
      - arxiv-submission-ui
    environment:
      MYSQL_USER: foouser
      MYSQL_PASSWORD: foopass
      MYSQL_ROOT_PASSWORD: foorootpassword
      MYSQL_DATABASE: submission
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  filemanager:
    << : *base-service
    image: arxiv/filemanager
    # You can uncomment these lines to build this from a local
    # repo. You may need to update `context`.
    build:
      context: ../arxiv-filemanager
      dockerfile: Dockerfile
    container_name: arxiv-filemanager
    volumes:
      - ./../arxiv-filemanager/filemanager/:/opt/arxiv/filemanager/
    networks:
      - arxiv-submission-ui

  compiler-localstack:
    image: atlassianlabs/localstack
    container_name: compiler-localstack
    networks:
      - arxiv-submission-ui
    ports:
      - "4572:4572"
      - "4568:4568"
    environment:
      USE_SSL: 'true'
      DEBUG: 'true'

  compiler-api:
    << : *base-service
    image: arxiv/compiler
    # You can uncomment these lines to build this from a local
    # repo. You may need to update `context`.
    build:
       context: ../arxiv-compiler
       dockerfile: Dockerfile
    container_name: arxiv-compiler-api
    command: pipenv run flask run -h 0.0.0.0 -p 8100
    volumes:
      - ./../arxiv-compiler/compiler/:/opt/arxiv/compiler/
    ports:
      - 8100:8100
    depends_on:
      - compiler-localstack
      - compiler-worker
    networks:
      - arxiv-submission-ui

  compiler-worker:
    << : *base-service
    image: arxiv/compiler
    # You can uncomment these lines to build this from a local
    # repo. You may need to update `context`.
    build:
       context: ../arxiv-compiler
       dockerfile: Dockerfile
    container_name: arxiv-compiler-worker
    command: /opt/arxiv/start_worker.sh -A compiler.worker.celery_app --loglevel=INFO -E --concurrency=2
    volumes:
      - ./../arxiv-compiler/compiler/:/opt/arxiv/compiler/
    networks:
      - arxiv-submission-ui
    volumes:
      - "${HOST_SOURCE_ROOT}:/tmp"
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - compiler-localstack

  # This just runs once at the beginning to set up the database, then exits 0.
  #  submission-ui-create-database:
  #    << : *base-service
  #    image: arxiv/submission-ui
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: submission-ui-create-database
  #    command: python app.py
  #    networks:
  #      - arxiv-submission-ui

  submission-ui:
    << : *base-service
    image: arxiv/submission-ui
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arxiv-submission-ui
    #command: uwsgi --http-socket :8000 -M -t 3000 --manage-script-name --processes 8 --threads 1 --async 100 --ugreen  --mount /=wsgi.py --logformat "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"
    command: flask run -p 8000 -h 0.0.0.0
    volumes:
      - ./submit/:/opt/arxiv/submit/
    ports:
      - 8000:8000
    networks:
      - arxiv-submission-ui
  #  depends_on:
  #    - submission-ui-create-database


networks:
  arxiv-submission-ui:
