apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ default "submission-ui" .Values.ingress.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "submission-ui" .Values.name }}"
    service-group: ui
    env: "{{ .Values.namespace }}"
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
    ingress.kubernetes.io/auth-url: http://{{ .Values.authenticator.service }}.{{ .Values.namespace }}.svc.cluster.local/auth
    ingress.kubernetes.io/auth-response-headers: Authorization
    # ingress.kubernetes.io/rewrite-target: /
spec:
  tls:  # This will use the default certificate for the ingress controller.
  - hosts:
    - "{{ .Values.ingress.host }}"
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "{{ default "/" .Values.ingress.path }}"
        backend:
          serviceName: "{{ default "submission-ui" .Values.name }}"
          servicePort: 80
